server:
  port: 8095

spring:
  cloud:
    stream:
      defaultBinder: kafka
      default:
        contentType: application/json
      bindings:
        process_queue:
          destination: process_queue
        processed:
          destination: processed
      kafka:
        binder:
          brokers: localhost:9092
          zknodes: localhost:2181