version: '3'

services:
  kafka:
    container_name: kafka
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
